version: 3

dotenv: [".env"]

tasks:
  default:
    desc: "使用本地配置运行（默认）"
    deps: ["run:local"]

includes:
  base:
    taskfile: ./scripts/tasks/base
  build:
    taskfile: ./scripts/tasks/build
  run:
    taskfile: ./scripts/tasks/run
  deploy:
    taskfile: ./scripts/tasks/deploy
  format:
    taskfile: ./scripts/tasks/format
  test:
    taskfile: ./scripts/tasks/test